### PR TITLE
Make some fields optional

### LINKED ISSUE #17: Make fields optional
Many fields within chaosinventory should be optional, but currently all are required. Go through the models and make appropriate changes.

### PR DESCRIPTION
**Pull request by clerie**
Some fields shouldn't be required like tags.
Fixes #17

### CODE REVIEW

**Comment by em0lar** [comment]
Is it correct to only use `blank=True`?  As far as I know, it's better to set `null` and `blank` to `True`. Here's an explanation about the difference, if you didn't know already: https://stackoverflow.com/questions/8609192/what-is-the-difference-between-null-true-and-blank-true-in-django

**Comment by clerie** [comment]
True. You should omit `null` on string fields and I forgot checking the field types.

**Review by n0emis — APPROVED** [review]

**Review by em0lar — CHANGES_REQUESTED** [review]
Did you rebuild the migration after adding `null=True`?

**Comment by clerie** [comment]
> Did you rebuild the migration after adding `null=True`?
Forgot it.

**Review by em0lar — APPROVED** [review]

**Review by adnidor — APPROVED** [review]

**Pull request merged**
